#!/bin/bash
# Setup script for Oracle-Guided-RL paths
# This script helps configure paths for different clusters

set -e

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$SCRIPT_DIR"

echo "=========================================="
echo "Oracle-Guided-RL 路径配置脚本"
echo "=========================================="
echo ""
echo "当前项目目录: $PROJECT_ROOT"
echo ""

# Detect cluster
if [[ "$HOSTNAME" == *"expanse"* ]] || [[ "$HOSTNAME" == *"sdsc"* ]]; then
    CLUSTER="EXPANSE"
    DEFAULT_PROJECT_ROOT="/expanse/lustre/projects/chi157/jji3/Oracle-Guided-RL"
elif [[ "$PROJECT_ROOT" == *"/share/data"* ]]; then
    CLUSTER="RIPL"
    DEFAULT_PROJECT_ROOT="$PROJECT_ROOT"
else
    CLUSTER="UNKNOWN"
    DEFAULT_PROJECT_ROOT="$PROJECT_ROOT"
fi

echo "检测到的集群: $CLUSTER"
echo ""

# Ask user for project root
read -p "请输入项目根目录 [$DEFAULT_PROJECT_ROOT]: " USER_PROJECT_ROOT
PROJECT_ROOT="${USER_PROJECT_ROOT:-$DEFAULT_PROJECT_ROOT}"

# Create local paths config (gitignored)
LOCAL_PATHS_CONFIG="$SCRIPT_DIR/config/paths_local.yaml"
cat > "$LOCAL_PATHS_CONFIG" << EOF
# @package _global_
# Local path configuration (gitignored)
# This file is loaded automatically by config files that include /paths in defaults
# Generated by setup_paths.sh

# Override project_root here
project_root: $PROJECT_ROOT
EOF

echo ""
echo "✓ 已创建本地路径配置文件: $LOCAL_PATHS_CONFIG"
echo "  项目根目录: $PROJECT_ROOT"
echo ""

# Add to .gitignore if not already there
if ! grep -q "paths_local.yaml" "$SCRIPT_DIR/.gitignore" 2>/dev/null; then
    echo "config/paths_local.yaml" >> "$SCRIPT_DIR/.gitignore"
    echo "✓ 已添加 paths_local.yaml 到 .gitignore"
fi

# Note about environment variable (optional, not modifying ~/.bashrc)
echo ""
echo "⚠️  注意: 不修改 ~/.bashrc（推荐用于 HPC 集群）"
echo ""
echo "配置完成！"
echo ""
echo "使用方法:"
echo "  1. 配置文件会自动使用 paths_local.yaml 中的路径"
echo ""
echo "  2. 在 SLURM 脚本或交互式会话中设置环境变量（可选）:"
echo "     export ORACLES_PROJECT_ROOT=$PROJECT_ROOT"
echo "     export MUJOCO_GL=egl"
echo ""
echo "  3. 或在 SLURM 脚本中直接设置:"
echo "     #SBATCH ..."
echo "     export ORACLES_PROJECT_ROOT=$PROJECT_ROOT"
echo "     export MUJOCO_GL=egl"
echo ""

