ROOT_DIR: "/share/data/ripl/jjt/projects/oracles/results"
FILE_PATTERN: "eval_episodes_seed\\d+\\.csv"
COLUMN_MAPPING:
  global_step: step
  return: score
FILTERS:
  min_step: 39999
  max_step: 819999
  grid_points: 10000
NORMALIZATION:
  enabled: false
  baseline_score: 0.0
INTERPOLATION:
  enabled: true
PLOT_SETTINGS:
  x_label: "Environment Steps"
  y_label: "Score"
  title: "RL Evaluation Performance" # Set to null to disable
  figsize: [8, 5]
  font_size: 16
  legend_font_size: 14
USE_SUBFOLDERS: false
ALGO_DIRS:
  - "/share/data/ripl/jjt/projects/oracles/results/Quad_CUP_quadruped_run"
  - "/share/data/ripl/jjt/projects/oracles/results/Quad_LOKI_quadruped_run"
  - "/share/data/ripl/jjt/projects/oracles/results/Quad_MAPS_quadruped_run"
  - "/share/data/ripl/jjt/projects/oracles/results/Quad_qmix_quadruped_run"
ALGO_NAMES:
  - "CUP"
  - "LOKI"
  - "MAPS"
  - "QMIX"
SAVE_PATH: "/share/data/ripl/jjt/projects/oracles/viz_results/quadruped_eval.png"

